---
title: "BM2_HW4"
author: "JINGHAN LIU"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(psych)
library(MASS)
library(nnet)
```

##Question 1

```{r}
# set data
dat <- c(65, 34, 54, 47, 100, 100,
130, 141, 76, 116, 111, 191,
67, 130, 48, 105, 62, 104)
dat_tb<- array(dat, c(2, 3, 3),
dimnames = list(Contact = c("Low", "High"),
Response = c("Low.sat", "Median.sat", "High.sat"),
Area = c("Tower", "Apartment", "House")))
ftable(dat_tb)



## 1.1
home_type <- margin.table(dat_tb, margin =c(2, 3))
prop.table(home_type, margin = 2) %>% 
round(., 4)
chisq.test(home_type)
## 1.2
home_type <- margin.table(dat_tb, margin =c(1, 3))
prop.table(home_type, margin = 2) %>% round(., 4)
chisq.test(home_type)
## 1.3
contact <- margin.table(dat_tb, margin =c(1, 2))
prop.table(contact, margin = 1) %>% round(., 4)
chisq.test(contact)




```

### q2
```{r}
dat_full <- data.frame(low = as.vector(dat_tb[,1,]),
median = as.vector(dat_tb[,2,]),
high = as.vector(dat_tb[,3,]),
int = rep(c(1, 2), 3),
cate = rep(c(2, 1, 3), each = 2))
```

```{r}
# model 1 - without interaction
m1 <- multinom(cbind(dat_full$low, dat_full$median, dat_full$high)
~ factor(int) + factor(cate), data = dat_full)
summary(m1)
exp(coef(m1))
exp(confint(m1))

# model 2 - with interaction
m2 <- multinom(cbind(dat_full$low, dat_full$median, dat_full$high)
~ factor(int) + factor(cate) + factor(cate)*factor(int), data = dat_full)
summary(m2)
exp(coef(m2))
exp(confint(m2))

# likelihood ratio test
TS1 = deviance(m1) - deviance(m2)
p1= 1 - pchisq(TS1, 4)


# goodness of fit
pihat <- predict(m1, type = "probs")
m <- rowSums(dat_full[,1:3])
res.pearson <- (dat_full[,1:3]-pihat*m)/sqrt(pihat*m)
G.stat <- sum(res.pearson^2)
p4 <- 1-pchisq(G.stat, (6-4)*(3-1))
```
##q3

```{r}
freq <- c(dat_full$low, dat_full$median, dat_full$high)
res <- c(rep(c("L", "M", "H"), c(6, 6, 6)))
res <- factor(res, levels = c("L", "M", "H"), ordered = T)
dat_ord <- data.frame(res = res, int = rep(dat_full$int, 3),
cate = rep(dat_full$cate, 3), freq = freq)
m5 <- polr(res ~ factor(int) + factor(cate), dat_ord,
weights = freq, method = "logistic")
summary(m5)
exp(coef(m5))

exp(confint(m5))
m6 <- polr(res ~ factor(cate), dat_ord, weights = freq)
TS5 <- deviance(m6) - deviance(m5)
p5<- 1-pchisq(TS5, 1)
m7 <- polr(res ~ factor(int), dat_ord, weights = freq)
TS6 <- deviance(m7) - deviance(m5)
p6<- 1-pchisq(TS6, 2)

```


##q4
```{r}
#Pearson Chi-Square residuals from proportional odds model
pihat <- predict(m5, type = "probs")
m <- rowSums(dat_full[,1:3])
res.pearson <- ((dat_full[,1:3]-pihat*m)/sqrt(pihat*m))%>% 
  round(.,2) %>% 
  as.data.frame()
res.pearson

```

